version: '3.8'

services:
  db:
    image: postgres:15.1-alpine
    container_name: db
    env_file:
      - .env.prod
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    image: ${BASE_IMAGE_TAG:-factory_bot_image}
    command: /bin/bash -c "
      while !</dev/tcp/db/5432; do sleep 1; done;
      python manage.py migrate --no-input &&
      gunicorn core.wsgi:application -b 0.0.0.0:8000 --reload --workers 2 --timeout 6
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.prod
    restart: always

  bot:
    container_name: bot
    image: ${BASE_IMAGE_TAG:-factory_bot_image}
    env_file:
      - .env.prod
    depends_on:
      - web
      - db
    command: /bin/bash -c "cd .. && python bot.py"
    restart: always

volumes:
  postgres-data:
